In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(f"{a} \n {b}" )

[1 2 3 4] 
 [5 6 7 8]


In [5]:
c = a+b
print(c)

[ 6  8 10 12]


In [8]:
print(c.size)
print(c.nbytes)
print(c.shape)
print(c.sum())

4
16
(4,)
36


# Practice Sets

In [13]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())
print(x.std())

[1 2 3 4 5 6 7 8 9]
45
1
9
5.0
2.581988897471611


In [14]:
print(x[1:5])

[2 3 4 5]
