In [3]:
import numpy as np
print(np.__version__)

1.23.5


In [4]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.shape)#dimension of the array
print(b.size)

(2, 3)
6


In [12]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(x.shape)

(3, 3)


In [18]:
print(x[2][2])
print(x[1][2])

9
6


In [20]:
print(x.sum())

45


In [23]:
print(x.sum(axis=0))
print(x.sum(axis=1))


[12 15 18]
[ 6 15 24]
